#todo: complete this in class

language: python
python:
  - "2.6"
  - "2.7" 
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  
 notifications:
  email:
    recipients:
      - warshawmj1@gcc.edu
     on-success: never # default: change
     on-failure: always #default: always
  
 script: "python simple_tests.py"
