#todo: complete this in class

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  
notifications:
  email:
    recipients:
      - one@example.com
      - other@example.com
     on_success: never # default: change
     on_failure: always # default: always

script: "python simple_tests.py"
